[build]
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, DELETE, OPTIONS"
