[build]
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, DELETE, OPTIONS"

# SPA fallback so client routes like /gallery work on refresh/direct link
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
